name: Build ATM7 image to dockerhub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the pack (used for tagging the image)'
        required: true
      pack_url:
        description: '.zip url to download'
        required: true
      installer_type:
        description: Type of installer script to use
        required: true
        type: choice
        options:
          - full.v5
          - full.v4
          - dl.v3

jobs:
  build:
    uses: mhaii/curseforge-minecraft-server-docker/.github/workflows/build-image.yml@master
    with:
      dockerfile: openjdk17.${{ inputs.installer_type }}.Dockerfile
      version: ${{ inputs.version }}
      pack_url: ${{ inputs.pack_url }}
      image_name: mhaii/minecraft-all-the-mods-7
    secrets:
      image_repo_id: ${{ secrets.DOCKER_HUB_ID }}
      image_repo_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
