name: Build image to dockerhub

on:
  workflow_call:
    inputs:
      java_image_tag:
        required: false
        type: string
      java_final_image_tag:
        required: false
        type: string
      version:
        required: true
        type: string
      pack_url:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      image_repo_id:
        required: true
      image_repo_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.image_repo_id }}
        password: ${{ secrets.image_repo_password }}
    - name: Build the image
      uses: docker/build-push-action@v2
      with:
        build-args: |
          url=${{ inputs.pack_url }}
          base_build_image_tag=${{ inputs.java_image_tag }}
          base_final_image_tag=${{ inputs.java_final_image_tag || inputs.java_image_tag }}
        tags: |
          ${{ inputs.image_name }}:latest
          ${{ inputs.image_name }}:${{ inputs.version }}
        labels: |
          image.source=${{ github.event.repository.html_url }}
          image.created=${{ steps.prep.outputs.created }}
          image.revision=${{ github.sha }}
    - name: Push image to DockerHub
      run: |
        docker push ${{ inputs.image_name }}:latest
        docker push ${{ inputs.image_name }}:${{ inputs.version }}
