name: Build image to dockerhub

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
      version:
        required: true
        type: string
      pack_url:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      image_repo_id:
        required: true
      image_repo_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image_name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ inputs.version }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.image_repo_id }}
        password: ${{ secrets.image_repo_password }}
    - name: Build the image
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.dockerfile || 'openjdk11.Dockerfile' }}
        build-args: |
          url=${{ inputs.pack_url }}
          base_build_image_tag=${{ inputs.java_image_tag }}
          base_final_image_tag=${{ inputs.java_final_image_tag || inputs.java_image_tag }}
        platforms: linux/amd64,linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
